### ISSUE TITLE
Visual Studio Error

### ISSUE THREAD

**Issue by JoshKeegan** [JoshKeegan/xRetry#4]
Build works fine from command line, but failing in Visual Studio. Work out why
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		[SpecFlow] System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at xRetry.SpecFlowPlugin.GeneratorPlugin.customiseDependencies(Object sender, CustomizeDependenciesEventArgs eventArgs)
   at TechTalk.SpecFlow.Generator.Plugins.GeneratorPluginEvents.RaiseCustomizeDependencies(ObjectContainer container, SpecFlowProjectConfiguration specFlowProjectConfiguration)
   at TechTalk.SpecFlow.Generator.GeneratorContainerBuilder.CreateContainer(SpecFlowConfigurationHolder configurationHolder, ProjectSettings projectSettings, IEnumerable`1 generatorPlugins)
   at TechTalk.SpecFlow.Generator.TestGeneratorFactory.CreateGenerator(ProjectSettings projectSettings, IEnumerable`1 generatorPlugins)
   at SpecFlow.Tools.MsBuild.Generation.FeatureCodeBehindGenerator.InitializeProject(String projectPath, String rootNamespace, IEnumerable`1 generatorPlugins)
   at SpecFlow.Tools.MsBuild.Generation.FeatureFileCodeBehindGenerator.<GenerateFilesForProject>d__5.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SpecFlow.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTask.Execute()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
	UnitTests	C:\Users\josh.keegan\.nuget\packages\specflow.tools.msbuild.generation\3.0.213\build\SpecFlow.Tools.MsBuild.Generation.targets	78	
```

**Comment by JoshKeegan** [comment]
When run from Visual Studio (assume due to full fat MSBuild), the `xRetry.SpecFlowPlugin.dll` needs to have `System.CodeDom.dll` in the same directory.  
Includng it in the nuget package, although not ideal, fixes this issue.

This then shows up another problem...
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		[SpecFlow] System.TypeLoadException: Method 'SetTestMethod' in type 'xRetry.SpecFlowPlugin.XunitProviders.XUnitTestGeneratorProvider' from assembly 'xRetry.SpecFlowPlugin, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at xRetry.SpecFlowPlugin.GeneratorPlugin.customiseDependencies(Object sender, CustomizeDependenciesEventArgs eventArgs)
   at TechTalk.SpecFlow.Generator.Plugins.GeneratorPluginEvents.RaiseCustomizeDependencies(ObjectContainer container, SpecFlowProjectConfiguration specFlowProjectConfiguration)
   at TechTalk.SpecFlow.Generator.GeneratorContainerBuilder.CreateContainer(SpecFlowConfigurationHolder configurationHolder, ProjectSettings projectSettings, IEnumerable`1 generatorPlugins)
   at TechTalk.SpecFlow.Generator.TestGeneratorFactory.CreateGenerator(ProjectSettings projectSettings, IEnumerable`1 generatorPlugins)
   at SpecFlow.Tools.MsBuild.Generation.FeatureCodeBehindGenerator.InitializeProject(String projectPath, String rootNamespace, IEnumerable`1 generatorPlugins)
   at SpecFlow.Tools.MsBuild.Generation.FeatureFileCodeBehindGenerator.<GenerateFilesForProject>d__5.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SpecFlow.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTask.Execute()	TestSpecFlow	C:\Users\Josh\.nuget\packages\specflow.tools.msbuild.generation\3.0.213\build\SpecFlow.Tools.MsBuild.Generation.targets	78	

```

**Comment by JoshKeegan** [comment]
This issue is actually caused by Full Fat MSBuild (used by Visual Studio regardless of targeting .net core or framework) using .Net framework for its plugins, not dotnet core.
So regardless of whether you intend to support core or framework, the generator must support both.
